### ISSUE TITLE
In config, what does "serverAddress" stand for ?

### ISSUE THREAD

**Issue by alcalyn** [Nebuleuse/Nebuleuse#1]
When trying to install nebuleuse locally, version on master, I get:

```
listen tcp 192.168.0.79:8080: bind: cannot assign requested address
```

I guess this ip comes from `serverAddress` from `.config` file, but I don't find in documentation what does it means.

**Comment by Orygin** [comment]
Hello, Thanks for trying to use my project :)

The address you see is indeed coming from `serverAddress` and is defined in the config file.
This value is the address at which Nebuleuse will start listening to requests. This address is passed on to golang's http serve function. You can set it to your computer's LAN ip, or your loopback (127.0.0.1) or simply remove the IP leaving the port behind `:8080` to match every possible incoming request.

Remember that you should always configure a fresh install of nebuleuse by running `./Nebuleuse install` before attempting to use it

If you need any more help feel free to contact me.

**Comment by alcalyn** [comment]
Ok I understand, I could `GET /status` and it works. Thank you!
